name: Add License Header

on:
  push:
    paths:
      - '**/*.rs'  # Add paths or file types you want to include
  pull_request:
    paths:
      - '**/*.rs'  # Add paths or file types you want to include
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  add-license-header:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write  # If you need to add labels or comments

    steps:
    - name: Generate GitHub App Token
      id: generate_token
      uses: tibdex/github-app-token@v1
      with:
        app_id: ${{ vars.BTL_ACTIONS_BOT_APP_ID }}
        private_key: ${{ secrets.BTL_ACTIONS_BOT_PRIVATE_KEY }}

    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        token: ${{ steps.generate_token.outputs.token }}

    - name: Install Python (for running script)
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Append License Header to Files
      run: |
        # Define the license header template and comment prefix
        LICENSE_HEADER=$(cat license-header.txt)
        COMMENT_PREFIX="// "

        # Remove trailing whitespace from the license header
        LICENSE_HEADER=$(echo "$LICENSE_HEADER" | sed 's/[ \t]*$//g')

        # Comment out the license header
        LICENSE_HEADER_COMMENTED=$(echo "$LICENSE_HEADER" | sed "s|^|$COMMENT_PREFIX|")

        # Loop through all Rust source files
        for FILE in $(find . -name '*.rs'); do
          # Remove existing header (assume it's the first commented block)
          sed -i '/^\/\/ /d' "$FILE"
          
          # Prepend the new license header
          echo "$LICENSE_HEADER_COMMENTED" | cat - "$FILE" > temp && mv temp "$FILE"
        done

    - name: Check if any files were modified
      id: changes
      run: |
        if [ -n "$(git status --porcelain)" ]; then
          echo "changes=true" >> $GITHUB_OUTPUT
        else
          echo "changes=false" >> $GITHUB_OUTPUT
        fi

    - name: Create Pull Request with License Header Updates
      if: steps.changes.outputs.changes == 'true'
      uses: peter-evans/create-pull-request@v4
      with:
        token: ${{ steps.generate_token.outputs.token }}
        commit-message: "Update license header in source files"
        branch: license-header-updates
        title: "Update License Headers"
        body: |
          This pull request updates the license headers in the source files.
        labels: automated
