name: Add License Header

on:
  push:
    paths:
      - '**/*.rs'  # Add paths or file types you want to include
  pull_request:
    paths:
      - '**/*.rs'  # Add paths or file types you want to include
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  add-license-header:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Python (for running script)
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Append License Header to Files
      run: |
        #!/bin/bash

        # Define the license header template
        LICENSE_HEADER=$(cat license-header.txt)

        # Comment character (assuming Rust's comment style)
        COMMENT_PREFIX="// "

        # Check and comment out the license header only if not already commented
        LICENSE_HEADER_COMMENTED=$(echo "$LICENSE_HEADER" | sed -E "s|^([[:space:]]*)($COMMENT_PREFIX)?|\1$COMMENT_PREFIX|")

        # Loop through all source files and update the license header
        for FILE in $(find . -name '*.rs'); do
          # Determine the range of the existing commented block
          START_LINE=0
          END_LINE=0
          while IFS= read -r LINE || [ -n "$LINE" ]; do
            ((START_LINE++))
            if [[ $LINE =~ ^[[:space:]]*// ]]; then
              END_LINE=$START_LINE
            else
              break
            fi
          done < "$FILE"

          # Remove the existing header
          if [ $END_LINE -gt 0 ]; then
            tail -n +$((END_LINE + 1)) "$FILE" > temp && mv temp "$FILE"
          fi

          # Prepend the new license header
          echo "$LICENSE_HEADER_COMMENTED" | cat - "$FILE" > temp && mv temp "$FILE"
        done

    - name: Commit changes
      run: |
        git config --local user.name "GitHub Actions"
        git config --local user.email "actions@github.com"
        git add .
        git commit -m "Update license header in source files" || echo "No changes to commit"
        git push origin HEAD:${{ github.ref }}
