name: Enforce Signed Commits

on:
  pull_request:
    branches: ['main', 'master', '**']

jobs:
  enforce_signed_commits:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Verify GPG Signed Commits
        uses: tj-actions/verify-commit@v1
        with:
          fail_on_unsigned: true
