name: Enforce Signed Commits

on:
  pull_request:
    branches: ['main', 'master', '**']

jobs:
  enforce_signed_commits:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Enforce Signed Commits
        uses: webfactory/commitlint-action@v3
        with:
          commitlint_config: https://raw.githubusercontent.com/webfactory/commitlint-config-gpg-verified/master/index.js
